modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="food_mod"
version="1.1.1"
displayName="AlexNest's Food and Stuff Mod"
credits="Created using mod maker MCreator. Check it out!"
displayURL="https://mcreator.net"
authors="AlexNest"
description='''
My first mod, which adds a lot of stuff. Hope you'll like it!
'''

[[dependencies.food_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




